name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install Aftman
      with:
        version: v0.2.7
        token: ${{ SECRETS.GITHUB_TOKEN }}
      
    - name: Lint
      run: |
        selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v1.1.2
      with:
        version: v0.15.1
        token: ${{ SECRETS.GITHUB_TOKEN }}
        args: --check ./src
