name: Deploy to Roblox

on:
  pull_request:
    branches:
    - 'releases/**'

  

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    if: 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install Aftman
      with:
        version: v0.2.7
        token: ${{ SECRETS.GITHUB_TOKEN }}
    
    - run: rbxcloud experience publish -f game.rbxl -p 11370209099 -u 4046563377 -a ${{ secrets.ROBLOX_API_KEY }}
    
